image: Visual Studio 2019
platform: x64
configuration: Debug

before_build:
  - nuget restore

after_build: 7z a Latest.zip %APPVEYOR_BUILD_FOLDER%\Memory\bin\Debug\netstandard2.0\*

artifacts:
  path: Latest.zip
  name: Latest

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_BUILD_ID)
    release: Build $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    description: Latest Compile Date %APPVEYOR_REPO_COMMIT_TIMESTAMP%
    auth_token:
      secure: aefoG8dMwSeQHm/FO6ydUZ591jX/M5fOms12ehz1obL4hnj8P7AIVrWqhztUK0cm
    artifact: Latest.zip
    force_update: true
    draft: false
